export default [
  {
    id: 1,
    image: '/monegram.png',
    techs: ['React', 'Redux', 'Express', 'Styled Components'],
    exp: 'Income and expense tracker full stack application. I designed ,developed and maintain.',
    title: 'Monegram',
    live: 'https://react-takeall-app.netlify.app/',
    repo: 'https://github.com/salperen-jpg/react-ecommerce-app',
  },
  {
    id: 2,
    image: '/takeAll.png',
    techs: ['React', 'Auth0', 'Scss'],
    title: 'TakeAll',
    exp: 'Ecommerce application that can make user buy products.',
    live: 'https://github-user-search-app-react.netlify.app/',
    repo: 'https://github.com/salperen-jpg/github-user-app',
  },
  {
    id: 3,
    image: '/github.png',
    techs: ['React', 'Auth0', 'Styled Components'],
    title: 'Github User',
    exp: 'Small app allows user search for specific github profile.',
    live: 'https://github-user-search-app-react.netlify.app/',
    repo: 'https://github.com/salperen-jpg/github-user-app',
  },
  {
    id: 4,
    image: 'todo.png',
    techs: ['React', 'Auth0', 'Scss'],
    title: 'Todo',
    exp: 'Nice looking todo app , be more effective with what you are gonna do. ',
    live: 'https://react-todo-app-challenge.netlify.app/',
    repo: 'https://github.com/salperen-jpg/react-todo-app-redux',
  },
];
